### ISSUE TITLE
Play around git and github

### ISSUE THREAD

**Issue by maihuynhtruc** [directsale/learning#1]

**Comment by maihuynhtruc** [comment]
https://try.github.io/levels/1/challenges/1

**Comment by maihuynhtruc** [comment]
https://git-scm.com/docs

**Comment by buihoanghai** [comment]
https://git-scm.com/docs/gittutorial

**Comment by maihuynhtruc** [comment]
https://git-scm.com/book/vi/v1/Bắt-Đầu-Cơ-Bản-về-Git

**Comment by maihuynhtruc** [comment]
---------chuan practice git & github-----------
https://guides.github.com/activities/hello-world/

**Comment by maihuynhtruc** [comment]
---------chuan practice git & github-----------
http://rogerdudler.github.io/git-guide/index.vi.html

**Comment by maihuynhtruc** [comment]
---------chuan practice git & github-----------
https://earlwlkr.wordpress.com/2015/01/29/huong-dan-thao-tac-voi-git-qua-command-line-2/
or theo huong dan tuong buoc trong github

**Comment by maihuynhtruc** [comment]
![screenshot from 2018-03-07 11-03-34](https://user-images.githubusercontent.com/36816608/37071431-7bb749ee-21f7-11e8-8334-50ad863e2894.png)

**Comment by maihuynhtruc** [comment]
Initial project
npm init
npm install jasmine -g - D
![screenshot from 2018-03-07 11-07-37](https://user-images.githubusercontent.com/36816608/37071517-d2b236c8-21f7-11e8-870b-15f7759319b9.png)
jasmine init
jasmine examples
![screenshot from 2018-03-07 11-10-19](https://user-images.githubusercontent.com/36816608/37071587-265bb9ca-21f8-11e8-9fbc-e6af9514688e.png)
touch .gitignore
![screenshot from 2018-03-07 11-12-56](https://user-images.githubusercontent.com/36816608/37071670-9549dfd8-21f8-11e8-9b69-5ad2687c6863.png)
